# Generated by Django 5.1.4 on 2024-12-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dukaan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='title',
        ),
    ]
